version: '3.8'
services:
    php-apache-environment:
        container_name: EasySite
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./sources/:/var/www/html/
        ports:
            - 8001:80
            
    db:
        container_name: DB_EasySite
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Qwertyuiop1!
            MYSQL_DATABASE: EasySite
            MYSQL_USER: ngn
            MYSQL_PASSWORD: Qwertyuiop1!
        ports:
            - "9906:3306"
        volumes: 
            - ./sources/database/EasySite.sql:/docker-entrypoint-initdb.d/dump.sql
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - '8080:80'
    #     restart: always
    #     environment:
    #         PMA_HOST: db
    #     depends_on:
    #         - db